helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework import routers
from equipment.views import equipment_view
from account.views import registration_view, logout_view, login_view, account_view
from dashboard.views import index

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name='home'),
    path('register/', registration_view, name='register'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('logout/', logout_view, name='logout'),
    path('equipment/', include('equipment.urls')),
    path('ticket/', include('ticket.urls',namespace='ticket')),

    path('api/account/', include('account.api.urls', 'account_api')),
    

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path, include
from .views import (
    #create_ticket_view,
    edit_ticket_view,
    get_ticket_detail_view,
    all_ticket_view,
    CreateTicketView,
    TicketDetailView,
)
app_name = 'ticket'

urlpatterns = [
    path('', all_ticket_view, name='show_tickets'),
    path('create/', CreateTicketView.as_view(), name='create_ticket'),
    path('<int:pk>/edit', edit_ticket_view, name='edit_ticket'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),

    #api urls
    path('api/', include('ticket.api.urls', 'ticket_api'))
]

templates/snippets/aside.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item">
        <div class="btn-group">
            {% if request.user.is_authenticated %}
                <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
                <a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
                <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a></p>
            {% else %}
                <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
                <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
                <a class="btn btn-outline-primary"  href="{% url 'register' %}">Register</a>
            {% endif %}  
        </div>
        <!-- <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
          <i class="fas fa-th-large"></i>
        </a> -->
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      
    </ul>
  </nav>
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %} " alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">ODPP</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/user2-160x160.jpg' %} " class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">
            {% if request.user.is_authenticated %}
                <p>Hello, {{request.user.username}}</p>
            {% endif %}
          </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <!--<li class="nav-item has-treeview menu-open ">
            <a href="index.php" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="./index.html" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Home</p>
                </a>
              </li>
              
            </ul>
          </li>-->
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Dashboard                
              </p>
            </a>
          </li>
          
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Equipment
                <i class="fas fa-angle-left right"></i>
                <!-- <span class="badge badge-info right">6</span> -->
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'show_equipment' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Manage Equipment</p>
                </a>
              </li>
              
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Ticket
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'ticket:show_tickets' %} " class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Management Ticket</p>
                </a>
              </li>
              
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Users
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="show_users.php" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Management Users</p>
                </a>
              </li>
              
            </ul>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/snippets/footer.html
{% load static %}
<footer class="main-footer">
    <strong>Copyright &copy; <?php echo date("Y"); ?> <a href="#">techavenueug.com</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.3-pre
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %} "></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %} "></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %} "></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %} "></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %} "></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %} "></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %} "></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %} "></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %} "></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %} "></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %} "></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %} "></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %} "></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %} "></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %} "></script>
</body>
</html>

templates/snippets/header.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href=" {% static 'plugins/jqvmap/jqvmap.min.css' %}  ">
    <!-- Theme style -->
    <link rel="stylesheet" href=" {% static 'dist/css/adminlte.min.css' %} ">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href=" {% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %} ">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %} ">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css' %} ">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!--HEADER
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">
            {% if request.user.is_authenticated %}
            <p>Hello, {{request.user.username}}</p>
            {% endif %}
        </h5>
        <nav class="my-2 my-md-0 mr-md-3">
            {% if request.user.is_authenticated %}
                <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
                <a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
                <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a></p>
            {% else %}
                <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
                <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
                <a class="btn btn-outline-primary"  href="{% url 'register' %}">Register</a>
            {% endif %}
        </nav>
        
      </div>-->
      <!--END HEADER-->
    