helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework import routers
from equipment.views import equipment_view
from account.views import registration_view, logout_view, login_view, account_view
from dashboard.views import index

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name='home'),
    path('register/', registration_view, name='register'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),
    path('logout/', logout_view, name='logout'),
    path('equipment/', include('equipment.urls')),
    path('ticket/', include('ticket.urls',namespace='ticket')),

    path('api/account/', include('account.api.urls', 'account_api')),
    

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/api/urls.py
from django.urls import path, include
from ticket.api.views import (
    api_ticket_detail_view,
    api_update_ticket_view,
    api_delete_ticket_view,
    api_create_ticket_view,
    api_ticket_view
)


app_name = 'ticket'

urlpatterns = [
    path('', api_ticket_view, name='all'),
    path('<int:pk>/', api_ticket_detail_view, name='detail'),
    path('<int:pk>/update', api_update_ticket_view, name='update'),
    path('<int:pk>/delete', api_delete_ticket_view, name='delete'),
    path('create', api_create_ticket_view, name='create'),

    
]

ticket/urls.py
from django.urls import path, include
from .views import (
    #create_ticket_view,
    edit_ticket_view,
    get_ticket_detail_view,
    all_ticket_view,
    CreateTicketView,
    TicketDetailView,
)
app_name = 'ticket'

urlpatterns = [
    path('', all_ticket_view, name='show_tickets'),
    path('create/', CreateTicketView.as_view(), name='create_ticket'),
    path('<int:pk>/edit', edit_ticket_view, name='edit_ticket'),
    path('<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),

    #api urls
    path('api/', include('ticket.api.urls', 'ticket_api'))
]

ticket/models.py
from django.db import models
from account.models import Account
from datetime import datetime
from django.db.models.signals import post_save

# Create your models here.
category = (
    ('procamis','procamis'),
    ('internet','internet'),
    ('hardware','hardware'),
    ('software','software'),
    ('others','others'),
)
status = (
    
    ('open','open'),
    ('pending','pending'),
    ('resolved','resolved'),
    ('closed','closed'),
)
priority = (
    ('nuetral','nuetral'),
    ('low','low'),
    ('moderate','moderate'),
    ('high','high'),
)


class Ticket(models.Model):
    user = models.ForeignKey(Account, blank=True, null=True, on_delete=models.CASCADE)
    ticket_num = models.CharField(max_length=100)
    full_name = models.CharField(max_length=200, blank=False, null=False)
    station = models.CharField(max_length=100)
    ticket_category = models.CharField(max_length=100, choices=category)
    description = models.TextField(max_length=200)
    created_at = models.DateField(auto_now_add=True)
    

    def __str__(self):
        return self.ticket_num

class TicketStatus(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE ,blank=True, null=True)
    status = models.CharField(max_length=20, choices=status, default='general')
    priority = models.CharField(max_length=100, choices=priority, default='neutral')
    action_taken = models.TextField(max_length=100, null=True)
    technician = models.ForeignKey(Account, on_delete=models.SET_NULL, blank=True, null=True)
    updated_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.ticket.ticket_num

def create_ticket_status(sender, **kwargs):
    if kwargs['created']:
        ticket_status = TicketStatus.objects.create(ticket=kwargs['instance'])

post_save.connect(create_ticket_status, sender=Ticket)

ticket/forms.py
from django import forms
from .models import Ticket, TicketStatus

class TicketCreateForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('full_name', 'ticket_num','station','ticket_category', 'description')

class TicketStatusForm(forms.ModelForm):
    class Meta:
        model = TicketStatus
        fields = ('ticket','status', 'priority', 'action_taken','technician')


    

ticket/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from account.models import Account
from ticket.models import Ticket
from ticket.api.serializer import TicketSerializer

@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
def api_ticket_view(request):

    try:
        ticket_detail = Ticket.objects.all()
    except Ticket.DoesNotExist:
        return Response(status=status.HTTP_400_BAD_REQUEST)

    if request.method == "GET":
        serializer = TicketSerializer(ticket_detail, many=True)
        return Response(serializer.data)

@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
def api_ticket_detail_view(request, pk):

    try:
        ticket_detail = Ticket.objects.get(pk=pk)
    except Ticket.DoesNotExist:
        return Response(status=status.HTTP_400_BAD_REQUEST)

    if request.method == "GET":
        serializer = TicketSerializer(ticket_detail)
        return Response(serializer.data)

@api_view(['PUT', ])
@permission_classes((IsAuthenticated, ))
def api_update_ticket_view(request, pk):

    try:
        ticket_detail = Ticket.objects.get(pk=pk)
    except Ticket.DoesNotExist:
        return Response(status=status.HTTP_400_BAD_REQUEST)

    user = request.user
    if ticket_detail.user != user:
        return Response({'response': "You don't have permission to update this ticket"})

    if request.method == "PUT":
        serializer = TicketSerializer(ticket_detail, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data["success"] = "update successful"
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE', ])
@permission_classes((IsAuthenticated, ))
def api_delete_ticket_view(request, pk):

    try:
        ticket_detail = Ticket.objects.get(pk=pk)
    except Ticket.DoesNotExist:
        return Response(status=status.HTTP_400_BAD_REQUEST)

    user = request.user
    if ticket_detail.user != user:
        return Response({'response': "You don't have permission to delete this ticket"})

    if request.method == "DELETE":
        operation = ticket_detail.delete()
        data = {}
        if operation:
            data["success"] = "delete success"
        else:
            data["error"] = "delete failed"
        return Response(data=data)


@api_view(['POST', ])
@permission_classes((IsAuthenticated, ))
def api_create_ticket_view(request):
    account = request.user

    ticket = Ticket(user=account)
    if request.method == "POST":
        serializer = TicketSerializer(ticket, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

ticket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Ticket, TicketStatus
from account.models import Account
from .forms import TicketCreateForm, TicketStatusForm
from django.views.generic import View, ListView, DetailView
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def all_ticket_view(request):
    ticket = TicketStatus.objects.all()
    return render(request, 'ticket/show_tickets.html', {'ticket':ticket})

class TicketDetailView(View):
    def get(self, request, pk):
        context = {}
        ticket = get_object_or_404(TicketStatus, pk=pk)
        form = TicketStatusForm(instance=ticket)
        context = {
            'ticket_detail' : ticket,
            'status_form':form
        }
        return render(request, 'ticket/ticket_detail.html', context)
    def post(self, request, pk):
        context = {}
        ticket = get_object_or_404(TicketStatus, pk=pk)
        if self.request.method == "POST":
            
            form = TicketStatusForm(self.request.POST)
            if form.is_valid():
                ts = form.save(commit=False)
                ticket_num = form.cleaned_data.get('ticket_num')
                ticket_qs = Ticket.objects.filter(user = self.request.user, ticket_num = ticket_num)
                if ticket_qs.exists():
                    ticket = ticket_qs[0]
                ts.ticket = ticket
                form.save()
                return redirect("ticket:ticket_detail")
            else:
                form = TicketStatusForm(instance=ticket)
                context['status_form'] = form
        else:
            form = TicketStatusForm(instance=ticket)
            return render(self.request, 'ticket/ticket_detail.html', context)
        

def get_ticket_detail_view(request, pk):
    context = {}
    ticket = get_object_or_404(TicketStatus, pk=pk)
    form = TicketStatusForm(instance=ticket)
    context = {
        'ticket_detail' : ticket,
        'status_form':form
    }
    return render(request, 'ticket/ticket_detail.html', context)

def add_ticket_status_view(request, pk):
    context ={}
    if request.method == "POST":
        form = TicketStatusForm(request.POST)
        if form.is_valid():
            ts = form.save(commit=False)
            ticket_num = form.cleaned_data.get('ticket_num')
            ticket_qs = Ticket.objects.filter(user = request.user, ticket_num = ticket_num)
            if ticket_qs.exists():
                ticket = ticket_qs[0]
            ts.ticket = ticket
            form.save()
            return redirect("ticket:ticket_detail")
            
                
                



    


#def create_ticket_view(request):
    context = {}
    if request.method == "POST":
        form = TicketCreateForm(request.POST)
        if form.is_valid():
            tic = form.save(commit=False)
            tic.user = request.user
            form.save()
            return redirect('show_tickets')
        else:
            context['ticket_form'] = form
    else:
        form = TicketCreateForm()
        context['ticket_form'] = form
    return render(request, 'ticket/create_ticket.html', context)

def edit_ticket_view(request, pk):
    context = {}
    ticket = get_object_or_404(Ticket, pk=pk)

    if request.method == "POST":
        form  = TicketCreateForm(request.POST, instance=ticket)
        if form.is_valid():
            tk = form.save(commit=False)
            tk.user = request.user
            form.save()
            return redirect('show_tickets')
    else:
        form = TicketCreateForm(instance=ticket)
        context['ticket_form'] = form
    return render(request, 'ticket/edit_ticket.html', context)

#def edit_status_view(request, pk):
    context = {}
    ticket = get_object_or_404(Ticket, pk=pk)

    if request.method == "POST":
        form  = UpdateTicketForm(request.POST, instance=ticket)
        if form.is_valid():
            tk = form.save(commit=False)
            tk.user = request.user
            form.save()
            return redirect('ticket_detail')
    else:
        form = UpdateTicketForm(instance=ticket)
        context['ticket_form'] = form
    return render(request, 'ticket/ticket_detail.html', context)

class CreateTicketView(View):
    def get(self, *args, **kwargs):
        context = {}
        form = TicketCreateForm()
        context = {
            'form':form
        }

        return render(self.request, 'ticket/create_ticket.html', context)
    def post(self, *args, **kwargs):
        form = TicketCreateForm(self.request.POST or None)
        try:
            
            #ticket_status = get_object_or_404(Ticket, pk=pk)
            if form.is_valid:
                tick = form.save(commit=False)
                full_name = form.cleaned_data.get('full_name')
                ticket_num = form.cleaned_data.get('ticket_num')
                station = form.cleaned_data.get('station')
                ticket_category = form.cleaned_data.get('ticket_category')
                description = form.cleaned_data.get('description')
                tick = Ticket(
                    user = self.request.user,
                    ticket_num = ticket_num,
                    full_name = full_name,
                    station = station,
                    ticket_category = ticket_category,
                    description = description
                )
                form.save()
                return redirect("ticket:show_tickets")
            else:
                messages.info(self.request, "Form not valid")
                return redirect("create_ticket")

        except ObjectDoesNotExist:
            messages.warning(self.request, "You don't have a ticket")
            return redirect("ticket/create_ticket")


    def get(self, *args, **kwargs):
        try:
            ticket = TicketStatus.objects.get()
        except expression as identifier:
            pass

ticket/templates/ticket/create_ticket.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>CREATE TICKET</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %} ">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %} ">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  
  {% include 'snippets/aside.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Create Ticket</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Create ticket</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-10">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Create Ticket</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              {% for field in ticket_form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <p>{{ error }}</p>
                    </div>
                    
                {% endfor %}
            {% endfor %}

            {% if ticket_form.non_field_errors %}
                <div class="alert alert-danger">
                    <p>{{ticket_form.non_field_errors}}</p>
                </div>
            {% endif %}
              
              <form role="form" method="post"> {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label >Full Names</label>
                    <input type="text" class="form-control" placeholder="Enter Full Name" 
                    name="full_name" value="">
                  </div>
                  <div class="form-group">
                    <label >Ticket Number</label>
                    <input type="text" class="form-control" placeholder="Enter Ticket Number" 
                    name="ticket_num" value="">
                  </div>
                  <div class="form-group">
                    <label>DPP Station</label>
                      <input class="form-control" type="text" name="station" placeholder="Enter your station">      
                  </div>
                  <div class="form-group">
                      <label>Category of Request</label>
                        <select class="form-control" name="ticket_category">
                          
                          {% for value, name in form.fields.ticket_category.choices %}
                              <option value="{{ value }}">{{ name }}</option>
                          {% endfor %}
                           
                        </select>
                  </div>
                  
                  <div class="form-group">
                    <label >Description of Request</label>
                    <textarea class="form-control" rows="3" placeholder="Brief description of Request" name="description" ></textarea>
                  </div>
                  </div>
                  
                  
                <!-- /.card-body -->

                <div class="card-footer">
                 
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

            <!-- Form Element sizes -->
            
            <!-- /.card -->

            
            <!-- /.card -->

            <!-- Input addon -->
            
            <!-- /.card -->
            <!-- Horizontal Form -->
            
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">
            <!-- general form elements disabled -->
            
            <!-- /.card -->
            <!-- general form elements disabled -->
            
            <!-- /.card -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.3-pre
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %} "></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %} "></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %} "></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %} "></script>
<script type="text/javascript">
$(document).ready(function () {
  bsCustomFileInput.init();
});
</script>
</body>
</html>

ticket/templates/ticket/show_tickets.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--<meta http-equiv="refresh" content="10" >-->
  <title>SHOW EQUIPMENT</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %} ">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %} ">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.css' %} ">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %} ">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% include 'snippets/aside.html' %}
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Manage Ticket</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Show ticket</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Show Ticket</h3>
              <a class="btn btn-info float-right" name="new_equipment" style="color: white;" href="{% url 'ticket:create_ticket' %}">New Ticket</a>
              <!--show messages-->
            </div>
            <!-- Modal -->
            {% if success_message %}
                <div class="alert alert-success">
                  <p>{{success_message}}</p>
                </div>
            {% endif %}
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Ticket ID</th>
                  <th>Staff Name</th>
                  <th>Ticket Category</th>
                  <th>Ticket Description</th>
                  <th>Staff Station</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  
                  {% for tkt in ticket %}
                <tr>
                  <td><a href="" >{{ tkt.ticket.ticket_num }}</a></td>
                  <td>{{ tkt.ticket.full_name }}</td>
                  <td>{{ tkt.ticket.ticket_category}}</td>
                  <td>{{ tkt.ticket.description }}</td>
                  <td>{{ tkt.ticket.station }}</td>
                  <td><span class=" badge bg-success">{{ tkt.status}}</span></td>
                   
                    <td class="project-actions text-center">
                          <a class="btn btn-primary btn-sm" href="{% url 'ticket:ticket_detail' pk=tkt.pk %}" class="btn btn-primary">
                              <i class="fas fa-folder">
                              </i>
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="{% url 'ticket:edit_ticket' pk=tkt.pk %} ">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>
                          <a class="btn btn-danger btn-sm" href="#">
                              <i class="fas fa-trash">
                              </i>
                              Delete
                          </a>
                      </td>

                    
                  
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th>Ticket ID</th>
                    <th>Staff Name</th>
                    <th>Ticket Category</th>
                    <th>Ticket Description</th>
                    <th>Staff Station</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
          <!--modal-->
          
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.3-pre
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %} "></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.js' %} "></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %} "></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %} "></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %} "></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
</body>
</html>

    